kafka:
  consumer:
    key.deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    value.deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    bootstrap.servers: localhost:9092
    group.id: com.fortidata
    auto.offset.reset: latest
    enable.auto.commit: false
  producer:
    key.serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    value.serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    bootstrap.servers: localhost:9092
    client.id: streaming.analytics
    zookeeper.connect: localhost:2181
pipelinerule:
  type: classpath
  url: classpath:/pipeline.json
schemaregistry:
  url: http://localhost:9090/schemaregistry